### ISSUE TITLE
usuwanie/modyfikacja pp. znalezionych z dyfrakcji

### ISSUE THREAD

**Issue by djbyways** [sigrond/BorderRecognition#2]

**Comment by djbyways** [comment]
- pauzowanie na usunięcie/przesunięcie punktów
- pole wybierania indeksów potencjalnych punktów
- globalny optymalizator dla funkcji skalaryzującej

**Comment by sigrond** [comment]
dodane pole wybierania indeksów punktów do przeszukania. in commit: b13653d647518172d4ce06582dbd296fbaac947b

**Comment by sigrond** [comment]
in commit: 2861aaf8205324a974f749153fe6d03a6081d04b
- pola wybierania indeksów potencjalnych punktów brzegowych w obu kolorach
- symulowane wyżarzanie dla funkcji skalaryzującej wyboru ramki po jasności

**Comment by sigrond** [comment]
in commit: fcbb6cd6972ae7a48a2fa4acdc40d35f5403940b
- dodanie opcji edycji wybranych punktów brzegowych
