### ISSUE TITLE
Integracja z PikeReader'em

### ISSUE THREAD

**Issue by djbyways** [sigrond/BorderRecognition#3]
1. Ręczny celownik pobiera skądś stary - stały obrazek
2. Po zakończeniu BorderRecognition parametry muszą się przekazać do PikeReadera, także w celu dalszej poprawy różnymi metodami, może nawet jeszcze raz BR tylko z innymi ustawieniami
3. Ten wektor pp. to fajnie ale trzeba by po pierwsze rozdzielić na kolory a najlepiej wysłać do obrazka w postaci roipoly czy jak tam.
4. Na koniec trzeba pomyśleć, które okienka są naprawdę potrzebne, bo jest już mrowie

**Comment by sigrond** [comment]
1. Wystarczy kliknąć Zapisz, a potem AutoFind zamiast quicstart (służy ono do odpalania demonstracji i nie jest zintegrowane z PikeReaderem)
2. Jeśli wybrało się ręczny celownik wspomagany, to w celu przekazania parametrów do PikeReadera należy zamknąć jego okno.

**Comment by sigrond** [comment]
Poprawki do p. 3. w: 2861aaf8205324a974f749153fe6d03a6081d04b

**Comment by sigrond** [comment]
Wydaje się, że powyższe problemy zostały rozwiązane. Jeśli będzie potrzeba, to można wprowadzić więcej ulepszeń.
